services:
  test-worker:
    build:
      context: .
      dockerfile: ./test.dockerfile
    environment:
      - JAEGER_ENDPOINT=jaeger:4318
  jaeger:
    image: ${REGISTRY:-}jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
